export default {
  homeScreen: 'Home',
  searchScreen: 'Search',
  wishlistScreen: 'Wishlist',
  profileScreen: 'Profile',
  notificationScreen: 'Notification',
  messageScreen: 'Message',
  loginScreen: 'Login',
  signUpScreen: 'SignUp',
  offerScreen: 'Offer',
  changePasswordScreen: 'Change Password',
  editProfileScreen: 'Edit Profile',
  rootScreen: 'rootScreen',
  rootAuthScreen: 'rootAuthScreen',
  profileTab: 'profileTab',
  homeTab: 'homeTab',
  messageTab: 'messageTab',
  notificationTab: 'notificationTab',
  wishlistTab: 'wishlistTab',
} as const;